[package]
name = "chip8-emulator-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
sdl2 = {version = "0.37.0", features = ["unsafe_textures"]}
clap = {version = "4.5.31", features = ["derive"]}
