[package]
name = "chip8-emulator-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["unsafe_textures"]
